### ISSUE TITLE
Add support for specifying clang or gcc

### ISSUE THREAD

**Issue by digimokan** [digimokan/smart-build#1]
#### Description
Would be useful to specify using clang or gcc as a config file option, and especially as a cmd-line switch, for quick building and testing in another compiler.

#### Tasks

- [ ] Make breaking change to `.project_config` with these two lines:
```
# Compiler: "gnu", "llvm", or "-" for system-default compiler
-
```
- [ ] Mod `smart-build.sh` to pull compiler from `.project_config`, then override it with one of these cmd-line options if present:
```
-g, --use-gnu-compiler
-l, --use-llvm-compiler
```
- [ ] Mod the generated `CMakeLists.txt` to `read_config_list_field` this option, the conditionally set compiler with this:
```
set(CMAKE_C_COMPILER "gcc/clang")
set(CMAKE_CXX_COMPILER "g++/clang++")
```

**Comment by digimokan** [comment]
Pull Request #9 closes. No change to `.project_config`. Should be cmd-line option only - don't hard-code compiler type into config files.
