### ISSUE TITLE
Make smart-build return a useful exit code

### ISSUE THREAD

**Issue by digimokan** [digimokan/smart-build#2]
#### Description
Currently _smart-build_ builds, tests, cleans, etc and returns 0. Would be useful to return non-zero exit code if build/test/etc. fails.

#### Tasks
- [ ] Make _smart-build_ exit early (without testing) if build fails.
- [ ] Leave the `exit 0` at the end of `main()`. Have `build_project` and `run_tests` each return a unique error code in their respective functions if the build/test fails.
- [ ] Write unit test(s) to at least check
  * bad build
  * good build but bad tests
